export const resources = {
  documents: {
    label: "Gestão de documentos",
    table: "documents",
    order: "id DESC",
    id: "id",
    searchable: ["code", "title", "sector", "status", "owner_name"],
    formFields: [
      { name: "code", label: "Código", type: "text", required: true },
      { name: "title", label: "Título", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "version", label: "Versão", type: "text", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Aprovado", "Em revisão", "Obsoleto"],
        required: true,
      },
      { name: "owner_name", label: "Responsável", type: "text" },
      { name: "next_review", label: "Próxima revisão", type: "date" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "bar", groupBy: "sector", title: "Documentos por setor" },
  },
  purchases: {
    label: "Controle de compras",
    table: "purchases",
    order: "id DESC",
    id: "id",
    searchable: [
      "request_number",
      "sector",
      "item_description",
      "status",
      "requested_by",
    ],
    formFields: [
      {
        name: "request_number",
        label: "Solicitação",
        type: "text",
        required: true,
      },
      { name: "sector", label: "Setor", type: "text", required: true },
      {
        name: "item_description",
        label: "Descrição do item",
        type: "textarea",
        required: true,
      },
      { name: "supplier_id", label: "ID fornecedor", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Em cotação", "Aprovado", "Recebido", "Cancelado"],
        required: true,
      },
      { name: "total_amount", label: "Valor total", type: "number" },
      { name: "requested_by", label: "Solicitado por", type: "text" },
      { name: "requested_at", label: "Data da solicitação", type: "date" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "pie", groupBy: "status", title: "Compras por status" },
  },
  indicators: {
    label: "Indicadores de desempenho",
    table: "indicators",
    order: "id DESC",
    id: "id",
    searchable: ["name", "sector", "status", "month_label"],
    formFields: [
      { name: "name", label: "Indicador", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "unit", label: "Unidade", type: "text", required: true },
      { name: "target_value", label: "Meta", type: "number", required: true },
      { name: "current_value", label: "Atual", type: "number", required: true },
      {
        name: "trend",
        label: "Tendência",
        type: "select",
        options: ["up", "down", "stable"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["good", "warning", "critical"],
        required: true,
      },
      { name: "month_label", label: "Mês", type: "text", required: true },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "bar", groupBy: "status", title: "Indicadores por status" },
  },
  audits: {
    label: "Gestão de auditorias",
    table: "audits",
    order: "planned_date DESC",
    id: "id",
    searchable: ["code", "audit_type", "sector", "auditor_name", "status"],
    formFields: [
      { name: "code", label: "Código", type: "text", required: true },
      {
        name: "audit_type",
        label: "Tipo",
        type: "select",
        options: ["Interna", "Externa"],
        required: true,
      },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "auditor_name", label: "Auditor", type: "text", required: true },
      {
        name: "planned_date",
        label: "Data planejada",
        type: "date",
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Planejada", "Em andamento", "Concluída"],
        required: true,
      },
      { name: "summary", label: "Resumo", type: "textarea" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "pie", groupBy: "status", title: "Auditorias por status" },
  },
  audit_findings: {
    label: "Conformidades e não conformidades",
    table: "audit_findings",
    order: "id DESC",
    id: "id",
    searchable: [
      "clause_ref",
      "description",
      "finding_type",
      "severity",
      "responsible_name",
    ],
    formFields: [
      {
        name: "audit_id",
        label: "ID da auditoria",
        type: "number",
        required: true,
      },
      { name: "clause_ref", label: "Cláusula", type: "text" },
      {
        name: "description",
        label: "Descrição",
        type: "textarea",
        required: true,
      },
      {
        name: "finding_type",
        label: "Tipo",
        type: "select",
        options: ["Conformidade", "Não conformidade"],
        required: true,
      },
      {
        name: "severity",
        label: "Severidade",
        type: "select",
        options: ["Baixa", "Média", "Alta", "Crítica"],
        required: true,
      },
      { name: "evidence", label: "Evidência", type: "textarea" },
      { name: "responsible_name", label: "Responsável", type: "text" },
      { name: "due_date", label: "Prazo", type: "date" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "pie", groupBy: "finding_type", title: "Achados por tipo" },
  },
  complaints: {
    label: "Reclamações de clientes",
    table: "complaints",
    order: "id DESC",
    id: "id",
    searchable: [
      "protocol",
      "customer_name",
      "channel",
      "category",
      "sector",
      "status",
    ],
    formFields: [
      { name: "protocol", label: "Protocolo", type: "text", required: true },
      { name: "customer_name", label: "Cliente", type: "text", required: true },
      { name: "channel", label: "Canal", type: "text", required: true },
      { name: "category", label: "Categoria", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      {
        name: "priority",
        label: "Prioridade",
        type: "select",
        options: ["Baixa", "Média", "Alta"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Em andamento", "Resolvida", "Cancelada"],
        required: true,
      },
      {
        name: "description",
        label: "Descrição",
        type: "textarea",
        required: true,
      },
      { name: "solution", label: "Solução", type: "textarea" },
      { name: "opened_at", label: "Abertura", type: "date" },
      { name: "closed_at", label: "Fechamento", type: "date" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "bar", groupBy: "sector", title: "Reclamações por setor" },
  },
  processes: {
    label: "Gestão de processos",
    table: "processes",
    order: "id DESC",
    id: "id",
    searchable: [
      "name",
      "sector",
      "owner_name",
      "risk_level",
      "performance_status",
    ],
    formFields: [
      { name: "name", label: "Processo", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "owner_name", label: "Dono do processo", type: "text" },
      { name: "objective", label: "Objetivo", type: "textarea" },
      {
        name: "risk_level",
        label: "Nível de risco",
        type: "select",
        options: ["Baixo", "Médio", "Alto"],
      },
      {
        name: "performance_status",
        label: "Performance",
        type: "select",
        options: ["good", "warning", "critical"],
      },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "pie", groupBy: "risk_level", title: "Processos por risco" },
  },
  management_reviews: {
    label: "Análises críticas",
    table: "management_reviews",
    order: "meeting_date DESC",
    id: "id",
    searchable: ["chairperson", "agenda", "status"],
    formFields: [
      { name: "meeting_date", label: "Data", type: "date", required: true },
      {
        name: "chairperson",
        label: "Conduzida por",
        type: "text",
        required: true,
      },
      { name: "agenda", label: "Pauta", type: "textarea", required: true },
      { name: "decisions", label: "Decisões", type: "textarea" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Aberta", "Fechada"],
        required: true,
      },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: {
      type: "pie",
      groupBy: "status",
      title: "Análises críticas por status",
    },
  },
  actions: {
    label: "Plano de ação 5W2H",
    table: "actions",
    order: "id DESC",
    id: "id",
    searchable: ["title", "module_name", "who_name", "status"],
    formFields: [
      { name: "title", label: "Título", type: "text", required: true },
      { name: "module_name", label: "Módulo", type: "text", required: true },
      { name: "what_text", label: "What", type: "textarea", required: true },
      { name: "why_text", label: "Why", type: "textarea", required: true },
      { name: "where_text", label: "Where", type: "text" },
      { name: "when_date", label: "When", type: "date" },
      { name: "who_name", label: "Who", type: "text" },
      { name: "how_text", label: "How", type: "textarea" },
      { name: "how_much", label: "How much", type: "number" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Planejada", "Em andamento", "Concluída"],
        required: true,
      },
      { name: "progress", label: "Progresso", type: "number" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: {
      type: "bar",
      groupBy: "status",
      title: "Planos de ação por status",
    },
  },
  risks: {
    label: "Análise de riscos",
    table: "risks",
    order: "score DESC",
    id: "id",
    searchable: ["title", "sector", "category", "status"],
    formFields: [
      { name: "title", label: "Risco", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      {
        name: "probability",
        label: "Probabilidade",
        type: "number",
        required: true,
      },
      { name: "impact", label: "Impacto", type: "number", required: true },
      { name: "score", label: "Score", type: "number", required: true },
      { name: "category", label: "Categoria", type: "text", required: true },
      {
        name: "mitigation_plan",
        label: "Plano de mitigação",
        type: "textarea",
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Monitorado", "Tratando", "Aceito"],
        required: true,
      },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "bar", groupBy: "sector", title: "Riscos por setor" },
  },
  opportunities: {
    label: "Oportunidades",
    table: "opportunities",
    order: "id DESC",
    id: "id",
    searchable: ["title", "sector", "priority", "status"],
    formFields: [
      { name: "title", label: "Oportunidade", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "expected_gain", label: "Ganho esperado", type: "textarea" },
      {
        name: "priority",
        label: "Prioridade",
        type: "select",
        options: ["Baixa", "Média", "Alta"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Planejada", "Em avaliação", "Aprovada"],
        required: true,
      },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: {
      type: "pie",
      groupBy: "priority",
      title: "Oportunidades por prioridade",
    },
  },
  changes_log: {
    label: "Mudanças",
    table: "changes_log",
    order: "id DESC",
    id: "id",
    searchable: ["title", "sector", "change_type", "status"],
    formFields: [
      { name: "title", label: "Mudança", type: "text", required: true },
      { name: "sector", label: "Setor", type: "text", required: true },
      { name: "change_type", label: "Tipo", type: "text", required: true },
      {
        name: "impact_level",
        label: "Impacto",
        type: "select",
        options: ["Baixo", "Médio", "Alto"],
        required: true,
      },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Em implantação", "Aprovada", "Rejeitada"],
        required: true,
      },
      { name: "description", label: "Descrição", type: "textarea" },
      { name: "attachments", label: "Anexos/Evidências", type: "file" },
    ],
    chart: { type: "pie", groupBy: "status", title: "Mudanças por status" },
  },
};

export function getResourceConfig(resource) {
  return resources[resource];
}
